version: '3'
services:
  app:
    depends_on:
      - db
    image: node:18-alpine
    container_name: users_graphql
    restart: always
    command: sh -c "yarn install && yarn dev:migrations && yarn start:debug"
    networks: 
      - mynetwork
    ports:
      - ${PORT}:3000
      - 9229:9229
    working_dir: /app
    volumes:
      - ./graphql:/app
    environment:
      AUTH0_ISSUER_URL: ${AUTH0_ISSUER_URL}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  db:
    image: postgres
    container_name: users_db
    restart: always
    networks: 
      - mynetwork
    ports:
      - 5432:5432
    volumes:
      - ./graphql/database/create_user_db.sql:/docker-entrypoint-initdb.d/create_user_db.sql
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
networks:
  mynetwork:
    name: mynetwork