version: '3'
services:
  app:
    depends_on:
      - db
    image: node:18-alpine
    container_name: users_graphql
    restart: always
    command: sh -c "yarn install && yarn dev:migrations && yarn start:dev"
    ports:
      - ${PORT}:3000
    working_dir: /app
    volumes:
      - ./graphql:/app
    environment:
      AUTH0_ISSUER_URL: ${AUTH0_ISSUER_URL}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}